services:
  authentik-postgres:
    image: postgres:16-alpine
    container_name: authentik-postgres
    restart: unless-stopped
    network_mode: host
    command: -p 5434
    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD: ${AUTHENTIK_PG_PASS}
    volumes:
      - /mnt/Memory Card/docker-data/authentik-pg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authentik -U authentik -p 5434"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  immich-postgres:
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    container_name: immich-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD}
      POSTGRES_DB: immich
    volumes:
      - /mnt/Memory Card/docker-data/immich-pg:/var/lib/postgresql/data

  piped-postgres:
    image: postgres:15-alpine
    container_name: piped-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_DB: piped
      POSTGRES_USER: piped
      POSTGRES_PASSWORD: piped
      PGPORT: "5433"
    volumes:
      - /mnt/Memory Card/docker-data/piped-pg:/var/lib/postgresql/data

  immich-redis:
    image: redis:6.2-alpine
    container_name: immich-redis
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/Memory Card/docker-data/immich-redis:/data

  piped-redis:
    image: redis:7-alpine
    container_name: piped-redis
    restart: unless-stopped
    network_mode: host
    command: redis-server --port 6380
    volumes:
      - /mnt/Memory Card/docker-data/piped-redis:/data
