services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.cooldad.top
    network_mode: host
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=1
      - ENABLE_OPENDKIM=0
      - ENABLE_OPENDMARC=0
      - ENABLE_POLICYD_SPF=0
      - ENABLE_AMAVIS=0
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - SSL_TYPE=
      - PERMIT_DOCKER=none
      - NETWORK_INTERFACE=enp6s0
      - ONE_DIR=1
      - POSTMASTER_ADDRESS=postmaster@cooldad.top
      - ENABLE_IMAP=1
    restart: always

  snappymail:
    image: djmaze/snappymail:latest
    container_name: snappymail
    network_mode: host
    volumes:
      - ./docker-data/snappymail:/var/lib/snappymail
    depends_on:
      - mailserver
    restart: always
